### ISSUE TITLE
Need a manual on importing bitcoin wallet or/and private keys

### ISSUE THREAD

**Issue by kirillkovalenko** [fastbitcoin/fastbitcoin#3]
Since this fork is not based on the original bitcoin source code it would be nice to have a tutorial on how to properly import bitcoin wallet or/and private keys.

**Comment by Crusty567** [comment]
Appears that this is code that's forked from BTS

**Comment by Nakamoto-san** [comment]
Appears that the code is forked from BTS

**Comment by keyeh** [comment]
Need instructions on how to import segwit keys also
